### ISSUE TITLE
nimbus failed?

### ISSUE THREAD

**Issue by duffqiu** [obaidsalikeen/storm-marathon#2]
if nimbus is crashed or failed, marathon will run it on another machine, right?
if that, the nimbus's ip will be changed. then how to let supervisor know that?

**Comment by obaidsalikeen** [comment]
Hi, If nimbus goes down, Marathon will redeploy another instance and with the help of HAProxy it will be discover-able by other services.  Please check-out the youtube link that I have specified in the references. You will get a good idea about service ports etc.
